import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
// import ChildLayout from "./newpage/layout";
// import NewPage from "./newpage/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Srishti Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        {children}
        {/* <ChildLayout /> */}
      </body>
    </html>
  );
}
